version: "3.9"
services:



  Foyer:
    container_name: foyer
    build: .\MicroServiceFoyer
    ports:
      - "9094:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/foyersarra?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/

    image: foyer
    restart: unless-stopped
    depends_on:
      - Eureka
      - db-mysql


  Eureka:
    container_name: eurekasaraah
    build: .\EurekaServer
    hostname: serviceregistry
    ports:
      - "8761:8761"
    image: eurekasarah
    environment:
      - eureka.client.serviceUrl.defaultZone=http://serviceregistry:8761/eureka/


  db-mysql:
    image: "mysql:5.6"
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root  #indisponsable pour la conteneurisation
      #- MYSQL_DATABASE=job
    ports:
      - "3307:3306"
    restart: unless-stopped


  api-gateway:
    build: .\MS_API_Gateway
    image: apigatewaysarah
    ports:
      - "8086:8086"  # Port mapping pour l'API Gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - "Eureka"
      - "Foyer"











