spring.application.name=projectAPIGetway
#spring.application.name=api-gateway
server.port=8086

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.client.service-url.defaultZone=http://eurekaali:8761/eureka/
eureka.client.register-with-eureka=true

